# Site settings
title: Huisstijldocument - Inter-Actief
email: fancie@inter-actief.net
description: > # this means to ignore newlines until "baseurl:"
  Op deze prachtige website kan je alle details over de huisstijl van Inter-*Actief* vinden.
baseurl: "/fancie-huisstijldocument" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  Inter-Actief

# Build settings
markdown: kramdown
